# Generated by Django 4.1 on 2023-04-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('const', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=50)),
                ('chosung', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('barcode', models.CharField(max_length=15)),
                ('expiration_date', models.DateTimeField()),
                ('size', models.CharField(choices=[('SMALL', 'SMALL'), ('LARGE', 'LARGE')], max_length=5)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
