# Generated by Django 4.1 on 2023-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_chosung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chosung',
            field=models.CharField(max_length=50),
        ),
    ]
